### ISSUE TITLE
joss review - minor typos etc

### ISSUE THREAD

**Issue by jsta** [sgrieve/spatial_efd#1]
Hi - I am going to list any minor typos and inconsistencies that I find in my review in this issue thread.

https://github.com/openjournals/joss-reviews/issues/189

**Comment by jsta** [comment]
The usage section of the README says to use a file called 'Shapefile.shp` but this file does not exist. I tried 'example_data.shp' but it only has 5 polygons (not 20).

**Comment by sgrieve** [comment]
Thanks for spotting this! I have corrected the filenames and also provided the relative path to the shapefile to try and make things clearer. I have also corrected the indexing of example_data.shp, so that the example code now generates the figures included in the readme.

**Comment by jsta** [comment]
The README makes it sound like `spatial_efd.plotComparison(ax, coeffs, harmonic, x, y, rotation=0.)` should show a plot. I found that it does not produce a figure unless `InitPlot` is called first and `SavePlot` is called afterwards. People who are uneasy digging into the source code might not discover this?

**Comment by jsta** [comment]
I am having difficulty producing the results from the normalized example:

```
import spatial_efd
shp = spatial_efd.LoadGeometries('spatial_efd/spatial_efd/tests/example_data.shp')

harmonic = 20

x, y, centroid = spatial_efd.ProcessGeometryNorm(shp[1])
coeffs = spatial_efd.CalculateEFD(x, y, harmonic)
coeffs, rotation = spatial_efd.normalize_efd(coeffs, size_invariant=True)

ax = spatial_efd.InitPlot()
spatial_efd.plotComparison(ax, coeffs, harmonic, x, y, rotation=rotation)
spatial_efd.SavePlot(ax, harmonic, 'normtest', 'png')
```

![Imgur](http://i.imgur.com/6HsYRYY.png)

**Comment by sgrieve** [comment]
There was a mistake in the code in the readme, in order to get the shapefile and the Fourier ellipse to align, the normalize_efd method has to be called with size_invariant=False, which produces the correct figure.
![normtest_20](https://cloud.githubusercontent.com/assets/10617231/23415488/3a8f1252-fdd7-11e6-84f1-deea61a66fcf.png)

I have added an additional comment to highlight this within the code block with the aim of making this clearer to the user.

**Comment by sgrieve** [comment]
I have added the initplot and saveplot methods to the readme to better demonstrate the functionality of the plotcomparison method.

**Comment by jsta** [comment]
OK, its working for me now.

It seems that one of the code blocks you edited is not rendered on the repo main page. Maybe because its missing a newline? I'm not too familiar with `rst` syntax.

**Comment by jsta** [comment]
I accidentally ran `saveShapefile` with `prj` set to a file that doesn't exist and there was no error thrown. This might be a worthwhile defensive programming test.

**Comment by jsta** [comment]
My last comment is more of style suggestion. I think it would be helpful to break-up the documentation into separate sections dealing with either normalized analyses or spatial analyses rather than switching back and forth.

**Comment by sgrieve** [comment]
I have fixed the code block in the readme, you are correct, it needed a blank line.

`saveShapefile` already had error handling so that it would not crash if an incorrect filename was supplied. I have made this more clear to the user by adding warnings if an invalid file is supplied. As the prj file is optional I don't want to throw an error but hopefully the warning will alert the user that something has gone wrong.

**Comment by sgrieve** [comment]
I have restructured the readme to now have two explicit sections, one dealing with spatial coordinates and one with normalized coordinates, so hopefully the readme is more useful.  I have also fixed a few other typos I spotted. Since there are no other comments I am going to close this issue.

Thanks for the feedback!
